# Generated by Django 4.2.6 on 2023-10-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccessForAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        choices=[("HOME", "HOME"), ("DETAIL", "DETAIL")],
                        max_length=455,
                        verbose_name="Página",
                    ),
                ),
                (
                    "accessed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Acessado em"),
                ),
                (
                    "ip",
                    models.CharField(
                        max_length=50, verbose_name="Endereço IP do Acesso"
                    ),
                ),
            ],
            options={
                "verbose_name": "Acessos",
                "verbose_name_plural": "Acessos",
            },
        ),
    ]
